# 02 - Estruturas de controle
Vamos aprender sobre estruturas de controle, instalação de bibliotecas e geração de gráficos, por meio de atividades práticas.

Crie uma nova branch (versão) do repositório:

```bash
git branch semana2
```

Faça o checkout nessa nova branch:

```bash
git checkout semana2
```

<hr />

## Atividade 1
Faça na linguagem Python uma função que verifica se um número é perfeito.

Um número é perfeito se a soma dos divisores for igual a ele mesmo (ex: 6 = 1 + 2 + 3).

In [2]:
def perfeito(n: int) -> bool:
    if n < 1:
        return False

    sum_divisors = 0
    for i in range(1, n):
        if n % i == 0:
            sum_divisors += i

    return sum_divisors == n


def main():
    assert perfeito(6) == True
    assert perfeito(7) == False
    assert perfeito(-1) == False


if __name__ == "__main__":
    main()

## Atividade 2
Faça na linguagem Python uma função que calcula o fatorial de um número.

O fatorial de um número é o produto do número por todos os antecessores positivos.

In [ ]:
def fatorial(n: int) -> int:
    if n < 0:
        raise ValueError("O número deve ser não negativo.")

    result = 1
    i = n
    while i > 1:
        result *= i
        i -= 1

    return result

def main():
    assert fatorial(5) == 120
    assert fatorial(0) == 1
    try:
        fatorial(-1)
    except ValueError as error:
        assert str(error) == "O número deve ser não negativo."

if __name__ == "__main__":
    main()

## Atividade 3
Faça na linguagem Python uma função que verifica se um número é primo.

Um número que só pode ser dividido por um e por ele mesmo.

In [8]:
def primo(numero: int) -> bool:
    if numero <= 1:
        return False
    
    for i in range(2, int(numero ** 0.5) + 1):
        if numero % i == 0:
            return False
            
    return True


def main():
    numero = 8
    if primo(numero):
        print(f"O número {numero} é primo!")
    else:
        print(f"O número {numero} não é primo.")


if __name__ == "__main__":
    main()

O número 8 não é primo.


## Atividade 4
Faça na linguagem Python uma função que calcula a soma dos dígitos.

Caso número negativo, dispare uma mensagem de erro (ex: 123, 1 + 2 + 3 = 6).

In [10]:
def soma_digitos(numero: int) -> int:
    return sum(int(digito) for digito in str(abs(numero)))


def main():
    numero = 12345968324412
    print(f"A soma dos dígitos de {numero} é {soma_digitos(numero)}")


if __name__ == "__main__":
    main()

A soma dos dígitos de 12345968324412 é 54


## Atividade 5
A partir de agora, vamos usar um ambiente virtual para execução dos nossos códigos.

Em Python, *venv* é um módulo que permite criar ambientes virtuais isolados, fundamentais para manter as dependências de cada projeto separadas e evitar conflitos com outras aplicações:

```bash
python3 -m venv .venv
source .venv/bin/activate
```

Para sair do ambiente, utilize o comando:

```bash
deactivate
```

Instale e importe a biblioteca NumPy, que é fundamental para computação científica em Python, oferecendo suporte para arrays e matrizes multidimensionais, além de uma vasta coleção de funções matemáticas de alto nível para operar eficientemente. Para instalar, utilize o comando:

In [6]:
%pip install numpy


[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


Escreva um algoritmo que realize o seguinte produto matricial:

 [1, 2, 3],  
  [4, 5, 6],  
  [7, 8, 9]  

multiplicado por:

 [11, 12, 13],  
  [14, 15, 16],  
  [17, 18, 19] 

In [11]:
import numpy as np


def main():
    A = np.array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ])

    B = np.array([
        [11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]
    ])

    resultado = np.dot(A, B) 

    print("Resultado da multiplicação matricial:")
    print(resultado)


if __name__ == "__main__":
    main()

Resultado da multiplicação matricial:
[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


## Versionando o código

Submeta a branch para o servidor:

```bash
git add .
git commit -m "Semana 2"
git push origin semana2
```